<?php

/**
 * Implementation of hook_install().
 */
function ca_business_directory_install() {
  variable_set('ca_business_directory_list_template', 'ca_business_directory_list_template_one');
  variable_set('ca_business_directory_node_template', 'ca_business_directory_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_business_directory_uninstall() {
  variable_del('ca_business_directory_list_template');
  variable_del('ca_business_directory_node_template');
}
