<?php

include_once('ca_business_directory.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_business_directory_perm() {
  return array('ca_business_directory change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_business_directory_menu() {
  $items['admin/settings/ca_business_directory'] = array(
    'title' => 'CA Business Directory: Admin',
    'description' => 'Change the look and feel of the ca_business_directory module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_business_directory_admin_settings_form'),
    'access arguments' => array('ca_business_directory change templates'),
    'file' => 'ca_business_directory.admin.inc',
    'file path' => drupal_get_path('module', 'ca_business_directory') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_business_directory_action_info() {
  return array(
    'ca_business_directory_add_business_directory_admin_action' => array(
      'type' => 'user',
      'description' => t('Add business directory administrator role'),
    ),
    'ca_business_directory_remove_business_directory_admin_action' => array(
      'type' => 'user',
      'description' => t('Remove business directory administrator role'),
    ),
  );
}

function ca_business_directory_add_business_directory_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'business directory administrator') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_business_directory_add_business_directory_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Business Directory Administrator',
  );
  return $form;
}

function ca_business_directory_add_business_directory_admin_action_submit(&$form, &$form_state) {
  
}

function ca_business_directory_remove_business_directory_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'business directory administrator') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_business_directory_remove_business_directory_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Business Directory Administrator',
  );
  return $form;
}

function ca_business_directory_remove_business_directory_admin_action_submit(&$form, &$form_state) {
  
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_business_directory_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_business_directory_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_business_directory' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_business_directory') . "/css/ca_business_directory.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_business_directory_views_pre_render(&$view) {
  if ($view->name == 'business directory') {
    drupal_add_css(drupal_get_path('module', 'ca_business_directory') . "/css/ca_business_directory.css", 'module', 'all', FALSE);
  }
}

